apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: upload-buffering-middleware
  namespace: nextcloud-system
spec:
  buffering:
    maxRequestBodyBytes: 10737418240  # 10 GB
    memRequestBodyBytes: 33554432      # 32 MB
    retryExpression: "IsNetworkError() && Attempts() < 3"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-route
  namespace: nextcloud-system
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`drive.unity-workspace.com`) || Host(`gateway.unity-workspace.com`) || Host(`10.1.16.200`) || Host(`10.1.16.11`) || Host(`10.1.16.12`) || Host(`10.1.16.13`)
    middlewares:
    - name: nextcloud-security-headers
      namespace: nextcloud-system
    - name: upload-buffering-middleware
      namespace: nextcloud-system
    - name: nextcloud-strip-prefix
      namespace: nextcloud-system
    services:
    - name: nextcloud-service
      port: 8080
      sticky:
        cookie:
          httpOnly: true
          name: nextcloud_session_sticky
          secure: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-route-tls
  namespace: nextcloud-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`drive.unity-workspace.com`) || Host(`gateway.unity-workspace.com`) || Host(`10.1.16.200`) || Host(`10.1.16.11`) || Host(`10.1.16.12`) || Host(`10.1.16.13`)
    middlewares:
    - name: nextcloud-security-headers
      namespace: nextcloud-system
    - name: upload-buffering-middleware
      namespace: nextcloud-system
    - name: nextcloud-strip-prefix
      namespace: nextcloud-system
    services:
    - name: nextcloud-service
      port: 8080
      sticky:
        cookie:
          httpOnly: true
          name: nextcloud_session_sticky
          secure: true
  tls:
    options:
      name: tls13-strict
