apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"IPAddressPool","metadata":{"annotations":{},"name":"default","namespace":"metallb-system"},"spec":{"addresses":["10.1.16.200-10.1.16.200"]}}
    creationTimestamp: "2026-08-24T03:33:54Z"
    generation: 1
    name: default
    namespace: metallb-system
    resourceVersion: "1603905"
    uid: f71ef28f-fc23-48f3-9d33-1c20ed0e701e
  spec:
    addresses:
    - 10.1.16.200-10.1.16.200
    autoAssign: true
    avoidBuggyIPs: false
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"L2Advertisement","metadata":{"annotations":{},"name":"example","namespace":"metallb-system"},"spec":{"interfaces":["eth0"]}}
    creationTimestamp: "2026-08-24T03:33:55Z"
    generation: 1
    name: example
    namespace: metallb-system
    resourceVersion: "1603906"
    uid: d8ae9553-0ddf-47c8-8393-623b928b3165
  spec:
    interfaces:
    - eth0
kind: List
metadata:
  resourceVersion: ""
