apiVersion: v1
kind: Service
metadata:
  name: nextcloud-notify-push
  namespace: nextcloud-system
  labels:
    app: nextcloud-notify-push
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7867
    targetPort: 7867
    protocol: TCP
  selector:
    app: nextcloud-notify-push
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-notify-push
  namespace: nextcloud-system
  labels:
    app: nextcloud-notify-push
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-notify-push
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nextcloud-notify-push
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
      containers:
      - name: notify-push
        image: nextcloud:apache
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        command:
        - /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
        ports:
        - containerPort: 7867
          protocol: TCP
        env:
        - name: NEXTCLOUD_URL
          value: "http://nextcloud-service:8080"
        - name: DATABASE_URL
          value: "postgres://admin:<URL_ENCODED_DB_PASSWORD>@nextcloud-db-rw:5432/nextcloud"
        - name: REDIS_URL
          value: "redis://:<URL_ENCODED_VALKEY_PASSWORD>@nextcloud-valkey-node-0.nextcloud-valkey-headless:6379"
        - name: NEXTCLOUD_CONFIG_DIR
          value: "/var/www/html/config"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-app-pvc
