# Valkey High Availability (Sentinel) Helm Values for Nextcloud
# Chart: bitnami/valkey
# Namespace: nextcloud-system

architecture: replication

auth:
  enabled: true
  password: "R5d#2D@!5"

master:
  persistence:
    enabled: false

replica:
  replicaCount: 2
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

sentinel:
  enabled: true
  masterSet: myprimary
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

metrics:
  enabled: false
