apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: nextcloud-system
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:latest
        ports:
        - containerPort: 9980
        env:
        - name: domain
          value: ".*"
        - name: extra_params
          value: "--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:ssl.ssl_verification=false"
        - name: aliasgroup1
          value: "https://drive.unity-workspace.com:443,https://drive.unity-workspace.com,https://office.unity-workspace.com:443,https://office.unity-workspace.com,https://gateway.unity-workspace.com:443,https://gateway.unity-workspace.com"
        - name: username
          value: "<COLLABORA_ADMIN_USER>"
        - name: password
          value: "<COLLABORA_ADMIN_PASSWORD>"
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - CHOWN
            - FOWNER
            - MKNOD
            - SYS_CHROOT
        readinessProbe:
          httpGet:
            path: /hosting/discovery
            port: 9980
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
      hostAliases:
      - ip: "10.233.23.138"
        hostnames:
        - "drive.unity-workspace.com"
        - "office.unity-workspace.com"
        - "gateway.unity-workspace.com"
